language: r

sudo: required
cache: packages
bioc_required: true
warnings_are_errors: true

apt_packages:
 - libnetcdf-dev
 - udunits-bin
 - libudunits2-dev

r_github_packages:
    - wilsontom/FIEmspro
    - jasenfinch/metabolyseR

notifications:
    email:
    on_success: change
    on_failure: change
