language: r

sudo: required
cache: packages
bioc_required: true
warnings_are_errors: true

r_github_packages:
    - wilsontom/FIEmspro

notifications:
    email:
    on_success: change
    on_failure: change
